// <auto-generated />
using System;
using EmployeeManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305035608_AddEmailTemplates")]
    partial class AddEmailTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Api.Entities.ContractType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ContractTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9217),
                            Description = "Hợp đồng thử việc 2 tháng theo quy định",
                            DurationMonths = 2,
                            IsActive = true,
                            Name = "Thử việc 2 tháng"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9224),
                            Description = "Hợp đồng lao động có thời hạn 6 tháng",
                            DurationMonths = 6,
                            IsActive = true,
                            Name = "Hợp đồng 6 tháng"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9230),
                            Description = "Hợp đồng lao động có thời hạn 1 năm",
                            DurationMonths = 12,
                            IsActive = true,
                            Name = "Hợp đồng 12 tháng"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9234),
                            Description = "Hợp đồng lao động có thời hạn 2 năm",
                            DurationMonths = 24,
                            IsActive = true,
                            Name = "Hợp đồng 24 tháng"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9239),
                            Description = "Hợp đồng lao động không xác định thời hạn",
                            IsActive = true,
                            Name = "Không thời hạn"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee111111-1111-1111-1111-111111111111"),
                            BodyHtml = "<!DOCTYPE html>\r\n<html>\r\n<head><meta charset='UTF-8'></head>\r\n<body style='font-family: Arial, sans-serif;'>\r\n    <h2 style='color: #2563eb;'>Thông báo thời gian thử việc sắp kết thúc</h2>\r\n    <p>Kính gửi <strong>{EmployeeName}</strong>,</p>\r\n    <p>Thời gian thử việc của bạn sắp kết thúc. Dưới đây là thông tin chi tiết:</p>\r\n    <table style='border-collapse: collapse; margin: 20px 0;'>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Ngày kết thúc thử việc:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd;'><strong>{EndDate}</strong></td>\r\n        </tr>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Số ngày còn lại:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd; color: #dc2626;'><strong>{DaysRemaining} ngày</strong></td>\r\n        </tr>\r\n    </table>\r\n    <p>Vui lòng liên hệ bộ phận Nhân sự để biết thêm thông tin.</p>\r\n    <hr style='margin: 20px 0;'>\r\n    <p style='color: #666; font-size: 12px;'>Email tự động từ Hệ thống Quản lý Nhân sự</p>\r\n</body>\r\n</html>",
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9496),
                            Description = "Email gửi cho nhân viên khi thử việc sắp kết thúc",
                            IsActive = true,
                            Name = "Nhắc nhở thử việc (Nhân viên)",
                            Subject = "[Nhắc nhở] Thử việc của {EmployeeName} sắp kết thúc",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("ee222222-2222-2222-2222-222222222222"),
                            BodyHtml = "<!DOCTYPE html>\r\n<html>\r\n<head><meta charset='UTF-8'></head>\r\n<body style='font-family: Arial, sans-serif;'>\r\n    <h2 style='color: #2563eb;'>Nhắc nhở Thời gian thử việc sắp kết thúc</h2>\r\n    <table style='border-collapse: collapse; margin: 20px 0;'>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Họ và tên:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd;'><strong>{EmployeeName}</strong></td>\r\n        </tr>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Phòng ban:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd;'>{Department}</td>\r\n        </tr>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Ngày kết thúc thử việc:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd;'><strong>{EndDate}</strong></td>\r\n        </tr>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Số ngày còn lại:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd; color: #dc2626;'><strong>{DaysRemaining} ngày</strong></td>\r\n        </tr>\r\n    </table>\r\n    <p>Vui lòng xem xét đánh giá và quyết định gia hạn hợp đồng cho nhân viên này.</p>\r\n</body>\r\n</html>",
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9505),
                            Description = "Email gửi cho HR khi nhân viên sắp hết thử việc",
                            IsActive = true,
                            Name = "Nhắc nhở thử việc (HR)",
                            Subject = "[Nhắc nhở Thử việc] {EmployeeName} - Còn {DaysRemaining} ngày",
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("ee333333-3333-3333-3333-333333333333"),
                            BodyHtml = "<!DOCTYPE html>\r\n<html>\r\n<head><meta charset='UTF-8'></head>\r\n<body style='font-family: Arial, sans-serif;'>\r\n    <h2 style='color: #dc2626;'>Thông báo hợp đồng lao động sắp hết hạn</h2>\r\n    <p>Kính gửi <strong>{EmployeeName}</strong>,</p>\r\n    <p>Hợp đồng lao động của bạn sắp hết hạn. Dưới đây là thông tin chi tiết:</p>\r\n    <table style='border-collapse: collapse; margin: 20px 0;'>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Ngày hết hạn hợp đồng:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd;'><strong>{EndDate}</strong></td>\r\n        </tr>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Số ngày còn lại:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd; color: #dc2626;'><strong>{DaysRemaining} ngày</strong></td>\r\n        </tr>\r\n    </table>\r\n    <p>Vui lòng liên hệ bộ phận Nhân sự để thảo luận về việc gia hạn hợp đồng.</p>\r\n    <hr style='margin: 20px 0;'>\r\n    <p style='color: #666; font-size: 12px;'>Email tự động từ Hệ thống Quản lý Nhân sự</p>\r\n</body>\r\n</html>",
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9510),
                            Description = "Email gửi cho nhân viên khi hợp đồng sắp hết hạn",
                            IsActive = true,
                            Name = "Nhắc nhở hợp đồng (Nhân viên)",
                            Subject = "[Nhắc nhở] Hợp đồng của {EmployeeName} sắp hết hạn",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("ee444444-4444-4444-4444-444444444444"),
                            BodyHtml = "<!DOCTYPE html>\r\n<html>\r\n<head><meta charset='UTF-8'></head>\r\n<body style='font-family: Arial, sans-serif;'>\r\n    <h2 style='color: #dc2626;'>Nhắc nhở Hợp đồng lao động sắp hết hạn</h2>\r\n    <table style='border-collapse: collapse; margin: 20px 0;'>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Họ và tên:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd;'><strong>{EmployeeName}</strong></td>\r\n        </tr>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Phòng ban:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd;'>{Department}</td>\r\n        </tr>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Ngày hết hạn hợp đồng:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd;'><strong>{EndDate}</strong></td>\r\n        </tr>\r\n        <tr>\r\n            <td style='padding: 8px; border: 1px solid #ddd; background: #f8f9fa;'>Số ngày còn lại:</td>\r\n            <td style='padding: 8px; border: 1px solid #ddd; color: #dc2626;'><strong>{DaysRemaining} ngày</strong></td>\r\n        </tr>\r\n    </table>\r\n    <p>Vui lòng liên hệ nhân viên để thảo luận về việc gia hạn hợp đồng.</p>\r\n</body>\r\n</html>",
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9514),
                            Description = "Email gửi cho HR khi hợp đồng nhân viên sắp hết hạn",
                            IsActive = true,
                            Name = "Nhắc nhở hợp đồng (HR)",
                            Subject = "[Nhắc nhở Hợp đồng] {EmployeeName} - Còn {DaysRemaining} ngày",
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("ee555555-5555-5555-5555-555555555555"),
                            BodyHtml = "<!DOCTYPE html>\r\n<html>\r\n<head><meta charset='UTF-8'></head>\r\n<body style='font-family: Arial, sans-serif;'>\r\n    <div style='max-width: 600px; margin: 0 auto; background: #ff6b6b; border-radius: 12px; overflow: hidden;'>\r\n        <div style='background: #ffffff; padding: 30px; text-align: center;'>\r\n            <h1 style='color: #ff6b6b;'>🎂 Chúc Mừng Sinh Nhật!</h1>\r\n        </div>\r\n        <div style='padding: 40px 30px; background: #fff;'>\r\n            <h2 style='color: #333;'>Chào {EmployeeName} thân mến!</h2>\r\n            <p style='color: #666; line-height: 1.6;'>\r\n                Nhân dịp sinh nhật lần thứ <strong>{Age}</strong> của bạn, chúng tôi xin gửi đến bạn \r\n                những lời chúc tốt đẹp nhất!\r\n            </p>\r\n            <div style='background: #fff5f5; border-radius: 8px; padding: 20px; margin: 25px 0; border-left: 4px solid #ff6b6b;'>\r\n                <p><strong>Ngày sinh:</strong> {BirthDate}</p>\r\n                <p><strong>Tuổi:</strong> {Age} tuổi</p>\r\n            </div>\r\n            <p style='color: #666;'>\r\n                Chúc bạn luôn mạnh khỏe, hạnh phúc và thành công trong công việc!\r\n            </p>\r\n        </div>\r\n        <div style='background: #333; color: white; padding: 20px; text-align: center;'>\r\n            <p style='margin: 0;'>Email tự động từ Hệ thống Quản lý Nhân sự</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>",
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9570),
                            Description = "Email chúc mừng sinh nhật nhân viên",
                            IsActive = true,
                            Name = "Chúc mừng sinh nhật",
                            Subject = "🎂 Chúc Mừng Sinh Nhật - {EmployeeName}",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("ee666666-6666-6666-6666-666666666666"),
                            BodyHtml = "<!DOCTYPE html>\r\n<html>\r\n<head><meta charset='UTF-8'></head>\r\n<body style='font-family: Arial, sans-serif;'>\r\n    <div style='max-width: 700px; margin: 0 auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1);'>\r\n        <div style='background: #ff6b6b; padding: 30px; text-align: center; color: white;'>\r\n            <h1 style='margin: 0;'>🎉 Sinh nhật tháng {CurrentMonth}/{CurrentYear}</h1>\r\n        </div>\r\n        <div style='padding: 30px;'>\r\n            <h2 style='color: #333;'>Danh sách nhân viên có sinh nhật trong tháng:</h2>\r\n            {BirthdayList}\r\n            <p style='margin-top: 20px;'><strong>Tổng số:</strong> {TotalCount} nhân viên</p>\r\n        </div>\r\n        <div style='background: #333; color: white; padding: 20px; text-align: center;'>\r\n            <p style='margin: 0;'>Email tự động từ Hệ thống Nhân sự</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>",
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9575),
                            Description = "Email gửi HR danh sách sinh nhật trong tháng",
                            IsActive = true,
                            Name = "Danh sách sinh nhật tháng",
                            Subject = "[Thông báo] Danh sách sinh nhật tháng {CurrentMonth}/{CurrentYear}",
                            Type = 4
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("ProbationEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ProbationStartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DateOfBirth");

                    b.HasIndex("FullName");

                    b.HasIndex("ProbationEndDate");

                    b.HasIndex("Status");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.EmployeeContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContractTypeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EndDate");

                    b.HasIndex("EmployeeId", "EndDate");

                    b.ToTable("EmployeeContracts");
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.EmployeeEditHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FieldDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "ChangedAt");

                    b.ToTable("EmployeeEditHistories");
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.EmployeeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeFiles");
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ValueType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9421),
                            Description = "Số ngày thử việc mặc định",
                            Key = "DefaultProbationDays",
                            Value = "60",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9425),
                            Description = "Số ngày trước khi hết thử việc cần gửi nhắc nhở (cách nhau bởi dấu phẩy)",
                            Key = "ProbationReminderDaysBefore",
                            Value = "30,15,7,3,1",
                            ValueType = "array"
                        },
                        new
                        {
                            Id = new Guid("aaaa3333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9430),
                            Description = "Số ngày trước khi hết hợp đồng cần gửi nhắc nhở (cách nhau bởi dấu phẩy)",
                            Key = "ContractReminderDaysBefore",
                            Value = "30,15,7,3,1",
                            ValueType = "array"
                        },
                        new
                        {
                            Id = new Guid("aaaa4444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9435),
                            Description = "Danh sách email HR nhận thông báo (cách nhau bởi dấu phẩy)",
                            Key = "HrNotificationEmails",
                            Value = "hr@company.com",
                            ValueType = "string"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 5, 3, 56, 7, 596, DateTimeKind.Utc).AddTicks(9472),
                            Email = "admin@company.com",
                            FullName = "Quản trị viên hệ thống",
                            IsActive = true,
                            PasswordHash = "$2a$11$qJZhLzXXcJvRqR3ZP8H4R.VLkL3YW5aLnYkKjxkGXZ1Q8VqxKZqZa",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.EmployeeContract", b =>
                {
                    b.HasOne("EmployeeManagement.Api.Entities.ContractType", "ContractType")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeManagement.Api.Entities.Employee", "Employee")
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.EmployeeEditHistory", b =>
                {
                    b.HasOne("EmployeeManagement.Api.Entities.Employee", "Employee")
                        .WithMany("EditHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.EmployeeFile", b =>
                {
                    b.HasOne("EmployeeManagement.Api.Entities.Employee", "Employee")
                        .WithMany("Files")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.ContractType", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("EmployeeManagement.Api.Entities.Employee", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("EditHistories");

                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
